### ISSUE TITLE
 make Header containing Title and Logo - Html and CSS 

### ISSUE THREAD

**Issue by dnedaniele** [dnedaniele/cooknbook#6]
it is going to be a static title and logo

**Comment by SabineWanka** [comment]
@pfdzm Please take over this task if you can (when you have time) -Tony

**Comment by pfdzm** [comment]
@dnedaniele @SabineWanka please review pr #42

**Comment by pfdzm** [comment]
I will work on this shortly, to make the logo/title centered, remove the jumbotron background (looks weird with materialize's navbar)
